export const MATCH_CARD_ANIMATIONS_DURATION_SECONDS = 1;
export const MATCH_TEST_ANIMATION_UPDATE_TIME = 1;
export const MATCH_CARD_SHAKE_ITERATIONS_TIME = 4;
export const MATCH_CARD_PAINT_ITERATIONS_TIME = 1;
