services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: