export * from './IAuthData';
export * from './ICoordinates';
export * from './IDictionaryCard';
export * from './IDictionaryItem';
export * from './IStatistics';
export * from './ITestItem';
export * from './ITestSettings';
export * from './ITime';
export * from './TestItemType';
