export const appPaths = {
  TEST: '/test',
  REGISTRATION: '/registration',
  AUTHORIZATION: '/authorization',
  MODULES_CREATE: '/modules/create',
  NOT_FOUND: '/not-found',
  MODULES: '/modules',
  MODULE: '/modules/:id',
  MODULE_EDIT: '/modules/:id/edit',
  FOLDERS: '/folders',
  FOLDERS_CREATE: '/folders/create',
  FOLDER: '/folders/:id',
  FOLDER_EDIT: '/folders/:id/edit',
  MATCH_TEST: '/modules/match-test',
  MATCH_TEST_SETTINGS: '/modules/:id/match-test/settings',
  MATCH_TEST_RESULTS: '/modules/match-test/results',
  COURSES: '/courses',
  COURSE: '/courses/:id',
  COURSE_EDITOR: '/courses/:id/editor',
  NEW_COURSE_EDITOR: '/courses/editor',
  PROFILE: '/profile',
  ACHIEVEMENTS: '/achievements',
};
