export const appPaths = {
  TEST: '/test',
  REGISTRATION: '/registration',
  AUTHORIZATION: '/authorization',
  MODULES_CREATE: '/modules/create',
  NOT_FOUND: '/not-found',
  MODULES: '/modules',
  MODULE: '/modules/:id',
  MODULE_EDIT: '/modules/:id/edit',
  FOLDERS: '/folders',
  FOLDER: '/folders/:id',
  MATCH_TEST: '/modules/match-test',
  MATCH_TEST_SETTINGS: '/modules/:id/match-test/settings',
  MATCH_TEST_RESULTS: '/modules/match-test/results',
  COURSES: '/courses',
  COURSE: '/courses/:id',
  PROFILE: '/profile',
  ACHIEVEMENTS: '/achievements',
};
